version: '3.8'
services:
  micro_conversion:
    build:
      context: ./conversion/flaskr/
      dockerfile: Dockerfile
    command:  python app.py
    volumes:
      - ./download/:/usr/src/app/download/
      - ./uploaded/:/usr/src/app/uploaded/
    environment:
      URL_ARCHIVOS: http://5795-190-251-193-251.ngrok.io
    ports:
      - 8081:8081
    depends_on:
      - redis
    hostname: micro_conversion

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"

  worker:
    build:
      context: ./conversion/flaskr/
      dockerfile: Dockerfile
    entrypoint: ["/bin/sh","-c"]
    command: 
      - celery worker -A tareas --loglevel=info -P solo  
    volumes:
      - ./download/:/usr/src/app/download/
      - ./uploaded/:/usr/src/app/uploaded/
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0        
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      URL_ARCHIVOS: http://2e5b-190-251-193-251.ngrok.io
    links:
      - redis
    depends_on:
      - redis
  flower:
    image: mher/flower:0.9.5
    restart: unless-stopped
    command: ["flower", "--address=0.0.0.0", "--broker=redis://redis:6379/0","--port=5555", "--logging=DEBUG"]
    depends_on:
      - redis
    ports:
      - 5555:5555
volumes:
    redis_data:
    data_app: {} 
#- HTTPS_PROXY=http://connect2.virtual.uniandes.edu.co:443
#- HTTP_PROXY=http://connect2.virtual.uniandes.edu.co:443