version: '3.8'
services:
  micro_conversion:
    build:
      context: ./conversion/flaskr/
      dockerfile: Dockerfile
    command:  python app.py
    volumes:
      - ./download/:/usr/src/app/download/
      - ./uploaded/:/usr/src/app/uploaded/
    environment:
      URL_ARCHIVOS:  http://ec2-44-199-219-168.compute-1.amazonaws.com
    ports:
      - 81:81
    depends_on:
      - redis
    hostname: micro_conversion

  redis:
    container_name: redis
    image: redis:6-alpine
    ports:
      - "6379:6379"

  worker:
    build:
      context: ./conversion/flaskr
    entrypoint: ["/bin/sh","-c"]
    command:
      - celery -A tareas worker --pool=prefork --concurrency=20 --loglevel=info --logfile=download/celery.log
      #-  celery multi start A B -c:A 5 -c:B 10 -A tareas --loglevel=info 
      #docker-compose up --build --scale worker=3 
    volumes:
      - ./download/:/usr/src/app/download/
      - ./uploaded/:/usr/src/app/uploaded/
    environment:
      FLASK_DEBUG: 1
      CELERY_BROKER_URL: redis://redis:6379/0        
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      URL_ARCHIVOS:  http://ec2-44-199-219-168.compute-1.amazonaws.com
    links:
      - redis
    depends_on:
      - redis
  flower:
    image: mher/flower:0.9.5
    restart: unless-stopped
    command: ["flower", "--address=0.0.0.0", "--broker=redis://redis:6379/0","--port=5555", "--logging=DEBUG"]
    depends_on:
      - redis
    ports:
      - 5555:5555
volumes:
    redis_data:
    data_app: {} 
#- HTTPS_PROXY=http://connect2.virtual.uniandes.edu.co:443
#- HTTP_PROXY=http://connect2.virtual.uniandes.edu.co:443