#!/bin/bash
sudo su
sudo apt-get update -y
sudo dpkg --configure -a
sudo apt purge apache2 -y
sudo apt update -y
sudo rm /var/lib/apt/lists/lock
sudo rm /var/cache/apt/archives/lock
sudo rm /var/lib/dpkg/lock*
cd /home/ubuntu
sudo git clone --branch entrega2 https://javargas1029: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@github.com/MISW-4204-ComputacionEnNube/Proyecto-Grupo5-202120 
cd Proyecto-Grupo5-202120
sudo apt install nginx -y
sudo rm /etc/nginx/sites-available/default
sudo cp default /etc/nginx/sites-available/
sudo rm /etc/nginx/nginx.conf
sudo cp nginx.conf /etc/nginx/
sudo systemctl reload nginx
sudo apt-get install docker-ce docker-ce-cli containerd.io -y
sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
cd conversor
sudo iptables -A PREROUTING -t nat -i eth0 -p tcp --dport 80 -j REDIRECT --to-port 81
sudo docker-compose up --build
