version: '3.8'
services:
  api:
    build:
      context: ./api/
      dockerfile: Dockerfile
    command: 'python app.py'
    environment:
      AWS_ACCESS_KEY_ID: ASIA3I2TQPFIY2UJJ2F5
      AWS_SECRET_ACCESS_KEY_ID: 0RoLL7uIViK4QYVdRXLL2er0mRyBDxzudNbyz5aQ
      AWS_SESSION_TOKEN: FwoGZXIvYXdzEMf//////////wEaDFIMwzVRhpL23onJ1yLKAb5RSOZmoupq0co/O8vRnBylDw0h/3GetqsgdUTikCqEb91cKHqlsmfKnjlrnqEvHHei+klXDgYcU63MwwHYh5XwyjkMLVpCryMXu4fVRBZ9oer+1j4A8BBgi0f+m7lCWGNYtgloOjijSH6BU0ovk73IdJsVQuAAzkVLPfNizR/HZTIAh1Gs762aeYSIjatqp4ZdqQhCfjdRkFMCgnkpRO08kBviWjqKrFrVNkP0EBLIglq7gv/KiybCwL5BLjlFPMKr6YdDv5NlDw4opsuPjAYyLWx5DAkSJK4t6EJNrWkA5feBr36rMJVkxzPckKT/MQAMlOvIqSK4q9o/RTIPvQ==
    volumes:
      - ./uploads/:/usr/src/app/uploads/
      - ./downloads/:/usr/src/app/downloads/
    ports:
      - 8082:8082