version: '3.8'
services:
  api:
    build:
      context: ./api/
      dockerfile: Dockerfile
    command: 'python app.py'
    environment:
      AWS_ACCESS_KEY_ID: ASIA3I2TQPFI5RZY4KP2
      AWS_SECRET_ACCESS_KEY_ID: MM/ba0JPrJAKn5zqZBo2p2XDeNBBoSs3eB0RaI80
      AWS_SESSION_TOKEN: FwoGZXIvYXdzEKP//////////wEaDNvHgECkWW6f88lThCLKAXMSAC7A61CRXlxk0/p+WRb59WMNgXdld9v9owWGd2vZVegKjSoeeGqoqKa0mNVK4RvJhYA0xGtdoTDwOKsXjHtMMlNTEVfkNhUbm9x2huJnLFBTXqHWrRL5jidopjEJaIL619gdcrD0T2BA31W5xMJ8aSMnRW4fzAD5hJVS43QRVSALkERcjBKMcDJtIzkJCVqxGPph3LFr11s9DL8ijbOWW0EzHZIH6ivWr5TZo9D1GNMIOFJu2uObRr5oLsklC5MaYnjvllZex9Eo+sKHjAYyLYknfadmO7xwvOo0yFgaMTLp95KmUXlGQziUcYbwGL5E/BSz3oLa884HSMGlxA==
    volumes:
      - ./uploads/:/usr/src/app/uploads/
      - ./downloads/:/usr/src/app/downloads/
    ports:
      - 8082:8082