version: '3.8'
services:
  api:
    build:
      context: ./api/
      dockerfile: Dockerfile
    command: 'python app.py'
    environment:
      AWS_ACCESS_KEY_ID: ASIA3I2TQPFIUTWVDKXZ
      AWS_SECRET_ACCESS_KEY_ID: TnP6er2P5oo50kFbtk8sMEvzYqjCI4dYmLQ5+Q0M
      AWS_SESSION_TOKEN: FwoGZXIvYXdzEND//////////wEaDHBLhJUlHe2jMuqmRyLKAZDPcJBAOFRxegcB/AlZqi6h6dp7dbJ0xOwmJpUBz+5blIVcVgCMcia0YRPXRrtiJO+xIqw0VpJEOOdxm9UE7eRDFw/Ahdr6lZNFa50xo8+yS++CHRsyXwSNcP6r/b+MijYlc7vxhMaXndIqy9gSwa0+sWJbJLMXxL1yVooWLbx6c5zhrbNaU4W/W0abryd7gLE79TV0i8dk08m4wL+nwkc+sF7jbuqhHx97XLHcCzblZv0vce7drvi8bNZwCvzsD760Vf9Cli44oooosLqRjAYyLb03ln105NJaZgIcC52tTndpM6kjNWlCEYcswm+GZvOQeHI8BSvtiQCmKMxrUg==
    volumes:
      - ./uploads/:/usr/src/app/uploads/
      - ./downloads/:/usr/src/app/downloads/
    ports:
      - 8082:8082