version: '3.8'
services:
  api:
    build:
      context: ./api/
      dockerfile: Dockerfile
    command: 'python app.py'
    environment:
      AWS_ACCESS_KEY_ID: ASIA3I2TQPFIYM475AAD
      AWS_SECRET_ACCESS_KEY_ID: caut4RO+ulmW+EDcOiYbqppxRHErhFCZFQ2Y8TH2
      AWS_SESSION_TOKEN: FwoGZXIvYXdzEG4aDCsavfsZUR75GcBtRyLKAe3YDQCd4sLoDeDnSkB2zuPEkkZeGSiBzTllW7ArxiO0gr98fCtCPi1QyXX2HrGNb5V3/3EGsVJEeHebzuh7HtrtFLeMfFcpdXX2tL3Xc9oaNERJkUEuD6ugYrKMF+6dwNWxMGEJ6FKYP9nL0pOS8ubERy+I9UC1fQXDt7CSxZhKp2EUMvQ8eDe6uYXK+XUIKo3f5CyxHwUPKd+PeAaU33KrORkNBvKHa2Dk/e8dwiboARCP4e7s/3g2lz4wKRnHJQ9/CGag7Z8PDBEox5+0jAYyLcKdHoUpVnqDAqt34V7qaMdZftKZmtXclivnKAi787CaLUDM405Ia7vHu3T4UQ==
    volumes:
      - ./uploads/:/usr/src/app/uploads/
      - ./downloads/:/usr/src/app/downloads/
    ports:
      - 81:81