version: '3.8'
services:
  api:
    build:
      context: ./api/
      dockerfile: Dockerfile
    command: 'python app.py'
    environment:
      AWS_ACCESS_KEY_ID: ASIA3I2TQPFIYWL77WU4
      AWS_SECRET_ACCESS_KEY_ID: Nnsjm9hUUER+hWJ5R57vmTnHH56ZQK/vK67Urq5j
      AWS_SESSION_TOKEN: FwoGZXIvYXdzEAIaDB0aHzCayU9VNboAPiLKAdrvgRtIbcbSkxhtof2erPlralGCqGH18OnoSBdFn3CmtV79MxrpQvBkeHkpoB3dr8gjtBr1HuSOAJ1wn4kOOyS3ftVyEAJ2F3/dR/DNgFs5DlPwhhtqdEG3yMv3zrm3pO/AuQwwaf4+ieR1TXLA/rQhrK+JLbCMThuGeIur7OzLCBA2nADlDhHOSLEoGXn4M9YNpCYcCVW0B9dSb0PJ1/knCoipTtI5v0PM5Pg4uH8Q19rRlAoyLLh60gVKv56p8VybW4hXHVevmmwozMicjAYyLRUHm/LICxhkDU+mXkfMvUGTb/vBn1ENmo2EiK1FjCN2rOEr030tEgGc6WiuYg==
    volumes:
      - ./uploads/:/usr/src/app/uploads/
      - ./downloads/:/usr/src/app/downloads/
    ports:
      - 81:81


