version: '3.8'
services:
  api:
    build:
      context: ./api/
      dockerfile: Dockerfile
    command: 'python app.py'
    environment:
      AWS_ACCESS_KEY_ID: ASIA3I2TQPFIVK4YJFSW
      AWS_SECRET_ACCESS_KEY_ID: 5JWi0K3zB4kxUem4iuyjAaqbg8ZDLOQzujsAFBhW
      AWS_SESSION_TOKEN: FwoGZXIvYXdzEBAaDHehxVFZFtlVrvapbiLKAaUBNLs2GMFHjdFRLkwbajx4HllgmeaA79lTllCAR2MheGWHNdCUrSUmZfWCusGEJkhPRIsN9PTomK81JMJWEDBZ/wcIfW8/bQbCySN5460eYVsPu6MXlibAQtqjJDg7CePHx8kG9HO0thNJbVpYohaugQcmvLUTV2emyvBQjA1o0O6sfubwa/urVZv64qIne+KiH9kTwalFVAXoBtVlzTKuAOvv5t+jKYmGYeREXuEjaX+JLEs7vMsXELXPPhTr927vdIwqdtkDL40o8b+fjAYyLUXAzob7EtEGzl1Gc1fDa0xZ4prjEyIDFFf5D1765LER1gtQQgvDENgAp0CrtA==
    volumes:
      - ./uploads/:/usr/src/app/uploads/
      - ./downloads/:/usr/src/app/downloads/
    ports:
      - 81:81


