version: '3.8'
services:
  api:
    build:
      context: ./api/
      dockerfile: Dockerfile
    command: 'python app.py'
    environment:
      AWS_ACCESS_KEY_ID: ASIA3I2TQPFI7JO7WLXX
      AWS_SECRET_ACCESS_KEY_ID: Gb6Sgt42QNKgezY/EDi6JnRvTjPLuF58eME65iMz
      AWS_SESSION_TOKEN: FwoGZXIvYXdzEFUaDMp6zMi8DLrqWtW9hCLKAW2RkqasJxLWkvO5KbO1iWldKn7/ixAD+eS6fZW0CEFXZgnxDystQEnj3PS/tdozqAUUxCeGtZF3ajVbxa1IkYZNbjfkvaGuFeuJrreyRnjp/hpK9EEjisqROVzHvyJI4mjwtVCcVUfGUUuB69V0WubDWcRhopwt5NMiu651N+Uq7aBL3UVoBb051dl1kEAac1odjNsgt4T57kNyPDDDRKnc9P4PhP9pyOdWwXY9tjfYI4R6Kl6vJqjmaVuWDnpKZBJb4mGG39+kkV0o7K72iwYyLYRNXmRLuMYFZPdnfn3W4PadMt4dO1dJ6GnU6h9yO9GNmylVb0Qnepp4ENPA7g==
    volumes:
      - ./uploads/:/usr/src/app/uploads/
      - ./downloads/:/usr/src/app/downloads/
    ports:
      - 8082:8082
      
