version: '3.8'
services:
  api:
    build:
      context: ./api/
      dockerfile: Dockerfile
    command: 'python app.py'
    environment:
      AWS_ACCESS_KEY_ID: ASIA3I2TQPFIUDYMTBE5
      AWS_SECRET_ACCESS_KEY_ID: subV/6SsxdPi4RaxfLkmEL5dpYEyxJvOId+haqPs
      AWS_SESSION_TOKEN: FwoGZXIvYXdzEHgaDNjBZXtcRHN2wH0FwSLKATw5xJ6sIoJOjXdTKvlDyY4/0miMghM80Gk3n2/l5ZVrPo6NB+xTOocnKT2/ySigM9QdDiqVcYEhDo8X2+M+9ANs13dsgFtAfW+D3y21T4oZSASjWH/Iz2g9JXkMGLSYG8g7dMcUCbFTPa0NssQ7aVols1REn1wkv8W8Vmx081fNJ3Ha+27H5iwiRM063BU3uTfViGAxSAIOy0IRi3DKgxzIxFIJqyL+OM0t1nPN77/JNMdRdnBKA8WEyxyp5NxcGF9vNMAcPE6d7nAoo8K2jAYyLawTD7U3U26ju37fUu+Yrusu+GnAzFDzMs57iGuvSf1NQYbfZKznjpI2PJV2pw==
    volumes:
      - ./uploads/:/usr/src/app/uploads/
      - ./downloads/:/usr/src/app/downloads/
    ports:
      - 81:81