version: '3.8'
services:
  api:
    build:
      context: ./api/
      dockerfile: Dockerfile
    command: 'python app.py'
    environment:
      AWS_ACCESS_KEY_ID: ASIA3I2TQPFIWW65WXG4
      AWS_SECRET_ACCESS_KEY_ID: TJ8aSObvtwVlZNDtgIvbifZ1u8pEPgflG0eFPLgP
      AWS_SESSION_TOKEN: FwoGZXIvYXdzEDgaDDbxiBFtj937KsR3xiLKAUfv4FQz4Cm6x8DnsjapAV5OkyZt/gZiL/wrkAR7J09yCNZgpHNRruArrVl9CwVjbiF8P/N6PmM6/PVrRMzmUJn84r6OqCov7DmazUufBTRV0AoTBhvfBKKaZTcdK8ASnFZYC6PTTv+d6aNBcs9xNWYKB/HrMJH69jCti0/FHNqy8QpSOlpxt+KaSQ/CAtoawAomG1QWbjHf49qtfDB+hC988hfzrQWnpqXeGnw1eZj0DblXXL0mXRLJA/+fvlFIRCeZvZaZxSdRsRso4czgjAYyLXZkiGbPO44NrvFpAfxzvlDjEniOzNPGkV2kgC6uyUDEUvSOM2LI8YTu903vcA==
    volumes:
      - ./uploads/:/usr/src/app/uploads/
      - ./downloads/:/usr/src/app/downloads/
    ports:
      - 81:81