version: '3.8'
services:
  api:
    build:
      context: ./api/
      dockerfile: Dockerfile
    command: 'python app.py'
    environment:
      AWS_ACCESS_KEY_ID: ASIA3I2TQPFI6QG6P2HZ
      AWS_SECRET_ACCESS_KEY_ID: E8Qh88zkFzyq47ZSomXs2Ya/TdnM32iWSAGMxi9/
      AWS_SESSION_TOKEN: FwoGZXIvYXdzEPj//////////wEaDCWCJ03luHX8fj0j6iLKATt9kuzXjJmSKT9SPypXL5RRVnmrvXfwX64t1yDFgqspZ7iELgZJyNQLzjdwwvNhHzqD6fu7h/wUAJn1IpVCMioYCF5GsIoyZgh/zcyEk19XzwhVGIvLuEyiOf2FDqrGTuOsMMrsaPHdD3/Cwt0b3D2aLvRfnAy9NPSpIoHMpzDG1eaGVjjHqH0PbsbFRj4HrSFbwjRCZNgQ51JFrUTzA2LwJ8eVkiB8FcT66kMndp7jBMR0S+aTsFMLMrjC2CxOxMmNznmXDVraQz4o7JqajAYyLSj5edhqkSUHdR3teO8lflQfXMol4pbgh4CGgdJuJM3uOKGeZv8lZtDTp7kGAQ==
    volumes:
      - ./uploads/:/usr/src/app/uploads/
      - ./downloads/:/usr/src/app/downloads/
    ports:
      - 81:81