version: '3.8'
services:
  api:
    build:
      context: ./flaskr/
      dockerfile: Dockerfile
    command: 'python app.py'
    environment:
      URL_CONVERSOR: http://9523-190-251-193-251.ngrok.io
    ports:
      - 8080:8080
