version: '3.8'
services:
  api:
    build:
      context: ./flaskr/
      dockerfile: Dockerfile
    command: 'python app.py'
    environment:
      URL_CONVERSOR: http://a4ee-179-32-133-175.ngrok.io
    ports:
      - 8080:8080
