version: '3.8'
services:
  api:
    build:
      context: ./flaskr/
      dockerfile: Dockerfile
    command: 'python app.py'
    environment:
      URL_CONVERSOR: http://con-1-1566781069.us-east-1.elb.amazonaws.com
    ports:
      - 81:81