version: '3.8'
services:
  api:
    build:
      context: ./flaskr/
      dockerfile: Dockerfile
    command: 'python app.py'
    environment:
      URL_CONVERSOR: http://ec2-3-239-27-131.compute-1.amazonaws.com
      - 81:81
