version: '3.8'
services:
  api:
    build:
      context: ./flaskr/
      dockerfile: Dockerfile
    command: 'python app.py'
    environment:
      URL_CONVERSOR: http://ec2-54-236-35-242.compute-1.amazonaws.com
    ports:
      - 81:81
